env:
  browser: true
  jquery: true

plugins:
  - disable

extends: airbnb-base

rules:
  indent:
    - error
    - tab
  no-tabs: off
  global-require: off

globals:
  _: false
  $: false
  h: false
  hyperscript: false
  require: false
  projects: false
  
settings:
  eslint-plugin-disable:
    paths:
      import:
        - '*'
